### ISSUE TITLE
rake db:migrate fails

### ISSUE THREAD

**Issue by gaynetdinov** [bdurand/seamless_database_pool#11]
rake db:migrate produces the following error:

``` log
rake aborted! undefined local variable or method `abcs' for main:Object
```

Rails version is 3.2.11, but 3.2.10 and 3.2.9 version are affected too, with 3.2.8 rails error will be:

```
Task not supported by 'seamless_database_pool'
```

database.yml config:

``` yml
common: &common
  adapter: seamless_database_pool
  pool_adapter: postgresql
  username: postgres
  database: database
  encoding: UTF8
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *common
  master:
    host: localhost
    pool_weight: 0
  read_pool:
  - host: localhost
    pool_weight: 1
```

Thanks.
