### ISSUE TITLE
rake db:* commands failing

### ISSUE THREAD

**Issue by lloydmeta** [bdurand/seamless_database_pool#12]
Hi there,

I'm trying to use seamless_database_pool with Rails 3.2.11 and mysql2 and running into problems with the `rake db` commands.

My database.yml file

``` yaml
development: &dev
  adapter: seamless_database_pool
  database: rotterdam_sdp_test
  username: root
  password:
  port: 3306
  pool_adapter: mysql2
  master:
    port: 3306
    host: localhost
    username: root
    password:
```

When I run `rake db:create`, nothing happens - the rotterdam_sdp_test db doesn't actually get created.

When I run `rake db:migrate` after having created the database myself, I get 

undefined method `create_table' for class`ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter'

Any help would be greatly appreciated. Please let me know if you have any questions :)
